CC = g++
CFLAGS = -I/root/pydev/lib/python3.12/site-packages/torch/include/\
	-I/usr/local/lib/python3.11/dist-packages/torch/include/torch/csrc/api/include \
	-I/usr/include/python3.11

main: 
	$(CC) $(CFLAGS) lltm.cpp -c 